USE OneERP
GO

INSERT INTO Estado (est_nome,est_sigla) VALUES ('Acre','AC')
INSERT INTO Estado (est_nome,est_sigla) VALUES ('Alagoas','AL')
INSERT INTO Estado (est_nome,est_sigla) VALUES ('Amazonas','AM')
INSERT INTO Estado (est_nome,est_sigla) VALUES ('Amapá','AP')
INSERT INTO Estado (est_nome,est_sigla) VALUES ('Bahia','BA')
INSERT INTO Estado (est_nome,est_sigla) VALUES ('Ceará','CE')
INSERT INTO Estado (est_nome,est_sigla) VALUES ('Distrito Federal','DF')
INSERT INTO Estado (est_nome,est_sigla) VALUES ('Espirito Santo','ES')
INSERT INTO Estado (est_nome,est_sigla) VALUES ('Goiás','GO')
INSERT INTO Estado (est_nome,est_sigla) VALUES ('Maranhão','MA')
INSERT INTO Estado (est_nome,est_sigla) VALUES ('Minas Gerais','MG')
INSERT INTO Estado (est_nome,est_sigla) VALUES ('Mato Grosso do Sul','MS')
INSERT INTO Estado (est_nome,est_sigla) VALUES ('Mato Grosso','MT')
INSERT INTO Estado (est_nome,est_sigla) VALUES ('Pará','PA')
INSERT INTO Estado (est_nome,est_sigla) VALUES ('Paraíba','PB')
INSERT INTO Estado (est_nome,est_sigla) VALUES ('Pernambuco','PE')
INSERT INTO Estado (est_nome,est_sigla) VALUES ('Piauí','PI')
INSERT INTO Estado (est_nome,est_sigla) VALUES ('Paraná','PR')
INSERT INTO Estado (est_nome,est_sigla) VALUES ('Rio de Janeiro','RJ')
INSERT INTO Estado (est_nome,est_sigla) VALUES ('Rio Grande do Norte','RN')
INSERT INTO Estado (est_nome,est_sigla) VALUES ('Rondônia','RO')
INSERT INTO Estado (est_nome,est_sigla) VALUES ('Roraima','RR')
INSERT INTO Estado (est_nome,est_sigla) VALUES ('Rio Grande do Sul','RS')
INSERT INTO Estado (est_nome,est_sigla) VALUES ('Santa Catarina','SC')
INSERT INTO Estado (est_nome,est_sigla) VALUES ('Sergipe','SE')
INSERT INTO Estado (est_nome,est_sigla) VALUES ('São Paulo','SP')
INSERT INTO Estado (est_nome,est_sigla) VALUES ('Tocantins','TO')